#define SSID "your_ssid"
#define KEY "your_sup3r_s3cur3_p4ssw0rd"
#define OTA_PASSWORD "your_ota_password"
#define OTA_NAME "ESP8266Oven"
#define USE_SSD1306
#define RINGBUF_LEN 480
#define SAMPLE_INTERVAL 15000
#define STATE_TIMEOUT 300000
#define PID_INTERVAL 1000
#define START_TEMP 20
#define DEBOUNCE_TIME 50
#define BUTTON D0
#define RELAY D8
#define TC_DO D5
#define TC_CS D6
#define TC_CLK D7
#define BANDGAP 5
#define HEAT_OFFSET 15
#define PREHEAT_DIFF_THRESHOLD 35
